#!/bin/sh

TOP=$(git rev-parse --show-toplevel)

input="book.yml"
output="book.md"
cp "$input" "$output"

fold_file(){
    {
        printf \\n;
        <"$1" \
        sed -n '/^## See Also$/q;p' |
        sed 's/^<span [^>]*>//g; s/<\/span>//g;' | 
        awk '!NF {if (++n <= 2) print; next}; {n=0;print}';
        printf \\n;
    } >> "$output"
}

# Fold the introductory pages; use our manual order.
for slug in system-quality-attributes non-functional-requirements cross-functional-constraints cross-cutting-concerns; do
    fold_file "$TOP/doc/$slug/index.md"
done

# Fold the rest of the pages; use alphabetic order.
for slug in $(find "$TOP/doc" -type d -depth 1 | sort | grep -v "/\(system-quality-attributes\|non-functional-requirements\|cross-functional-constraints\|cross-cutting-concerns\)$" ); do
    fold_file "$slug/index.md"
done
